name: Build

on:
  push:
    tags:
      - 1.*

jobs:
  build:
    name: Build App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Upload (Windows)
      uses: actions/upload-artifact@v3
      with:
        name: BangumiRenamer_windows
        path: |
          dist
          
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: on.push.tags
        name: 🎉 on.push.tags
        draft: true
        body: |
          ## 新增
          - 新增内容

          ## 优化
          - 优化内容
