name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
          
    - name: Release
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        template: |
          ## Changes
          $CHANGES
