name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Upload (Windows)
      uses: actions/upload-artifact@v3
      with:
        name: BangumiRenamer_windows
        path: |
          dist
          
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, '1.')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: true
        body: olo
