name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest]

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Upload (Windows)
      if: ${{ runner.os == 'windows' }}
      uses: actions/upload-artifact@v3
      with:
        name: BangumiRenamer_windows
        path: |
          image
          
    - name: Create Release and Upload Release Asset
      uses: release-drafter/release-drafter@v5
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        template: |
          ## Changes
          $CHANGES
